In [46]:
import numpy as np
import pandas as pd

In [48]:
#  we will be using OLS method to train our model
class Bhai_ka_Multpile_LinearRegression():
    
    def __init__(self,optimizer = 'OLS',epoch = 500,lr = 0.01):
        self.optimizer = optimizer
        self.lr = lr
        self.epoch = epoch
        self.coeff = None
        self.intercept = None

    def initilize_params(self,X):
        n_features = X.shape[1]
        self.coeff = np.zeros(n_features)   # initilizing initital weights with 0
        self.intercept = 0
        
    #training happens using ols method
    def ols(self,X,y):
        X = np.insert(X,0,1,axis =1 )
        betas = np.linalg.inv(np.dot(X.T,X)).dot(X.T).dot(y)
            
        self.intercept = betas[0]
        self.coeff = betas[1:]

    #here training happens using SGD
    def SGD(self,X,y):
        # here first we need to initilize the params
        self.initilize_params(X)

        for i in range(self.epoch):
            # in stochastic gradient descent out batch size = 1
            for j in range(X.shape[0]):
                idx = np.random.randint(0,X.shape[0])
                Xi = X[idx]
                yi = y[idx]

                yhat = self.intercept + np.dot(Xi,self.coeff)

                # doing derivative 
                Dcoeff = -2 * (yi - yhat) * Xi
                Dintercept = -2 * (yi - yhat)

                # updating the parameter
                self.coeff = self.coeff - self.lr * Dcoeff
                self.intercept = self.intercept - self.lr * Dintercept
                
            if(i % 100 == 0) :
                y_pred = self.intercept + np.dot(X,self.coeff)
                print(f'after epoch {i} loss is { np.mean((y-y_pred)**2) }')
        
    def fit(self,X,y):
        if self.optimizer == 'OLS' :
            self.ols(X,y)
        if self.optimizer == 'SGD' :
            self.SGD(X,y)
        
    def predict(self,X):
        y_pred = self.intercept + np.dot(X,self.coeff)
        return y_pred

In [50]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=3, noise=10, random_state=42)

In [52]:
y[0:5]

array([-96.18275277, -60.28727313, -28.19368196, -12.69716964,
        11.71414867])

In [54]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [56]:
X_train.shape , y_train.shape

((800, 3), (800,))

In [58]:
X_test.shape , y_test.shape

((200, 3), (200,))

In [60]:
from sklearn.linear_model import LinearRegression
sklearn_model = LinearRegression()
sklearn_model

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [62]:
sklearn_model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [64]:
from sklearn.metrics import mean_absolute_error , mean_squared_error , r2_score

y_pred_sklearn = sklearn_model.predict(X_test)

print(f'sklearn ki test score is {sklearn_model.score(X_test,y_test)*100:.2f} %')
print(f'sklearn ki test MSE is {mean_squared_error(y_test,y_pred_sklearn)} ')
print(f'sklearn ki test MAE is {mean_absolute_error(y_test,y_pred_sklearn)} ')
print(f'sklearn ki test R2_score is {r2_score(y_test,y_pred_sklearn):.3f} %')

sklearn ki test score is 99.38 %
sklearn ki test MSE is 100.48489027843269 
sklearn ki test MAE is 8.238693553190242 
sklearn ki test R2_score is 0.994 %


### now we will train on bhai_ka_Multiplt_LinearRegression ( using OLS optimizer )

In [67]:
model_bhai_ka_ols_wala = Bhai_ka_Multpile_LinearRegression()

In [69]:
model_bhai_ka_ols_wala.fit(X_train,y_train) 

In [71]:
sklearn_model.coef_ , sklearn_model.intercept_

(array([98.3559076 , 82.80473759, 25.83193455]),
 np.float64(-0.044732055521219394))

In [73]:
model_bhai_ka_ols_wala.coeff , model_bhai_ka_ols_wala.intercept

(array([98.3559076 , 82.80473759, 25.83193455]),
 np.float64(-0.04473205552122267))

In [75]:
y_pred_bhai_k_ols_model_se = model_bhai_ka_ols_wala.predict(X_test)


print(f'Bhai ke model ki test MSE is {mean_squared_error(y_test, y_pred_bhai_k_ols_model_se):.4f}')
print(f'Bhai ke model ki test MAE is {mean_absolute_error(y_test, y_pred_bhai_k_ols_model_se):.4f}')
print(f'Bhai ke model ki test R2_score is {r2_score(y_test, y_pred_bhai_k_ols_model_se):.3f}')

Bhai ke model ki test MSE is 100.4849
Bhai ke model ki test MAE is 8.2387
Bhai ke model ki test R2_score is 0.994


### now we will train on bhai_ka_Multiplt_LinearRegression ( using SGD optimizer )

In [78]:
model_bhai_ka_sgd_wala = Bhai_ka_Multpile_LinearRegression(optimizer='SGD',epoch=1500)


In [80]:
model_bhai_ka_sgd_wala.fit(X_train,y_train)


after epoch 0 loss is 102.9173390696381
after epoch 100 loss is 100.45735675179778
after epoch 200 loss is 98.29501694714344
after epoch 300 loss is 100.18045591778038
after epoch 400 loss is 104.64547375969997
after epoch 500 loss is 99.96430574493712
after epoch 600 loss is 101.23050311682812
after epoch 700 loss is 99.6349903105841
after epoch 800 loss is 107.88957409377755
after epoch 900 loss is 99.37791378575247
after epoch 1000 loss is 100.69926894561554
after epoch 1100 loss is 106.30010239455248
after epoch 1200 loss is 99.89121397459668
after epoch 1300 loss is 100.45366174139464
after epoch 1400 loss is 97.8089869527245


In [81]:
model_bhai_ka_sgd_wala.coeff , model_bhai_ka_sgd_wala.intercept


(array([99.9197792 , 82.73584149, 27.77214837]),
 np.float64(-0.6195388989100108))

In [82]:
y_pred_bhai_k_SGD_model_se = model_bhai_ka_sgd_wala.predict(X_test)


print(f'Bhai ke model ki test MSE is {mean_squared_error(y_test, y_pred_bhai_k_SGD_model_se):.4f}')
print(f'Bhai ke model ki test MAE is {mean_absolute_error(y_test, y_pred_bhai_k_SGD_model_se):.4f}')
print(f'Bhai ke model ki test R2_score is {r2_score(y_test, y_pred_bhai_k_SGD_model_se):.3f}')

Bhai ke model ki test MSE is 104.1933
Bhai ke model ki test MAE is 8.3759
Bhai ke model ki test R2_score is 0.994


In [83]:
# comparing all three models

In [89]:
y_pred_sklearn = sklearn_model.predict(X_test)

print(f'sklearn ki model k coeff : {sklearn_model.coef_} \n and uska intercept : {sklearn_model.intercept_}  %')
print(f'sklearn ki test MSE is {mean_squared_error(y_test,y_pred_sklearn)} ')
print(f'sklearn ki test MAE is {mean_absolute_error(y_test,y_pred_sklearn)} ')
print(f'sklearn ki test R2_score is {r2_score(y_test,y_pred_sklearn):.3f} %')

print('\n','*'*110,'\n')

y_pred_bhai_k_ols_model_se = model_bhai_ka_ols_wala.predict(X_test)

print(f'Bhai ke ols wle model k coeff : {model_bhai_ka_ols_wala.coeff} \n and uska intercept : {model_bhai_ka_ols_wala.intercept}  %')
print(f'Bhai ke ols wle model ki test MSE is {mean_squared_error(y_test, y_pred_bhai_k_ols_model_se):.4f}')
print(f'Bhai ke ols wle model ki test MAE is {mean_absolute_error(y_test, y_pred_bhai_k_ols_model_se):.4f}')
print(f'Bhai ke ols wle model ki test R2_score is {r2_score(y_test, y_pred_bhai_k_ols_model_se):.3f}')

print('\n','*'*110,'\n')

y_pred_bhai_k_SGD_model_se = model_bhai_ka_sgd_wala.predict(X_test)

print(f'Bhai ke sgd wle model ki model k coeff : {model_bhai_ka_sgd_wala.coeff} \n and uska intercept : {model_bhai_ka_sgd_wala.intercept}  %')
print(f'Bhai ke sgd wle model ki test MSE is {mean_squared_error(y_test, y_pred_bhai_k_SGD_model_se):.4f}')
print(f'Bhai ke sgd wle model ki test MAE is {mean_absolute_error(y_test, y_pred_bhai_k_SGD_model_se):.4f}')
print(f'Bhai ke sgd wle model ki test R2_score is {r2_score(y_test, y_pred_bhai_k_SGD_model_se):.5f}')

sklearn ki model k coeff : [98.3559076  82.80473759 25.83193455] 
 and uska intercept : -0.044732055521219394  %
sklearn ki test MSE is 100.48489027843269 
sklearn ki test MAE is 8.238693553190242 
sklearn ki test R2_score is 0.994 %

 ************************************************************************************************************** 

Bhai ke ols wle model k coeff : [98.3559076  82.80473759 25.83193455] 
 and uska intercept : -0.04473205552122267  %
Bhai ke ols wle model ki test MSE is 100.4849
Bhai ke ols wle model ki test MAE is 8.2387
Bhai ke ols wle model ki test R2_score is 0.994

 ************************************************************************************************************** 

Bhai ke sgd wle model ki model k coeff : [99.9197792  82.73584149 27.77214837] 
 and uska intercept : -0.6195388989100108  %
Bhai ke sgd wle model ki test MSE is 104.1933
Bhai ke sgd wle model ki test MAE is 8.3759
Bhai ke sgd wle model ki test R2_score is 0.99355
